version: "3.5"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./web-api-ts/:/var/api
    tty: true
    entrypoint: npm run dev
